background {
    path = {{image}}
    blur_passes = 1
    contrast = 1
    brightness = 0.9
    vibrancy = 1
    vibrancy_darkness = 0.0
}

# GENERAL
general {
    no_fade_in = false
    no_fade_out = false
    grace = 0
    disable_loading_bar = false
}

input-field {
    size = 300, 50
    outline_thickness = 3
    dots_size = 0.33
    dots_spacing = 0.15
    dots_center = true
    dots_rounding = -1
    outer_color = {{colors.primary_fixed_dim.default.rgba}}
    inner_color = {{colors.surface_dim.default.rgba}}
    font_color = {{colors.on_surface.default.rgba}}
    fade_on_empty = true
    fade_timeout = 2000
    placeholder_text = <i><span foreground="{{colors.on_surface.default.hex}}"> Enter Password...</span></i>
    hide_input = false
    rounding = -1
    check_color = {{colors.primary_fixed_dim.default.rgba}}
    fail_color = rgba(255, 0, 0, 1)
    fail_transition = 300
    capslock_color = {{colors.on_primary_fixed.default.rgba}}
    numlock_color = {{colors.on_primary_fixed.default.rgba}}
    bothlock_color = {{colors.on_primary_fixed.default.rgba}}
    invert_numlock = false
    swap_font_color = {{colors.on_primary_fixed.default.rgba}}
    position = 0, 100
    halign = center
    valign = bottom
}

# time (hour)
label {
    monitor =
    text = cmd[update:1000] echo "$(date +'%I')"
    color = {{colors.primary_fixed_dim.default.rgba}}
    font_size = 200
    font_family = Montserrat Italic Bold
    position = -50, 200
    halign = center
    valign = center
    shadow_passes = 5
    shadow_size = 10
}

# time (minute)
label {
    monitor =
    text = cmd[update:1000] echo "$(date +'%M')"
    color = {{colors.primary_fixed_dim.default.rgba}}
    font_size = 200
    font_family = Montserrat Italic Bold
    position = 50, -10
    halign = center
    valign = center
    shadow_passes = 5
    shadow_size = 10
}

# date
label {
    monitor =
    text = cmd[update:1000] echo "$(date +'%d %B, %Y')"
    color = {{colors.on_surface.default.rgba}}
    font_size = 25
    font_family = Pacifico Regular
    position = 0, -150
    halign = center
    valign = center
    shadow_passes = 5
    shadow_size = 10
}
