# Matugen template for btop


# Colors should be in 6 or 2 character hexadecimal or single spaced rgb decimal: "#RRGGBB", "#BW" or "0-255 0-255 0-255"
# example for white: "#ffffff", "#ff" or "255 255 255".

# All graphs and meters can be gradients
# For single color graphs leave "mid" and "end" variable empty.
# Use "start" and "end" variables for two color gradient
# Use "start", "mid" and "end" for three color gradient

# Main background, empty for terminal default, need to be empty if you want transparent background
theme[main_bg]=""

# Main text color
theme[main_fg]="#dee3e5"

# Title color for boxes
theme[title]="#84d2e6"

# Highlight color for keyboard shortcuts
theme[hi_fg]="#b2cbd2"

# Background color of selected item in processes box
theme[selected_bg]="#84d2e6"

# Foreground color of selected item in processes box
theme[selected_fg]="#003640"

# Color of inactive/disabled text
theme[inactive_fg]="#bfc8cb"

# Misc colors for processes box including mini cpu graphs, details memory graph and details status text
theme[proc_misc]="#bec4eb"

# Cpu box outline color
theme[cpu_box]="#899295"

# Memory/disks box outline color
theme[mem_box]="#899295"

# Net up/down box outline color
theme[net_box]="#899295"

# Processes box outline color
theme[proc_box]="#899295"

# Box divider line and small boxes line color
theme[div_line]="#3f484b"

# Temperature graph colors
theme[temp_start]="#b2cbd2"
theme[temp_mid]="#84d2e6"
theme[temp_end]="#ffb4ab"

# CPU graph colors
theme[cpu_start]="#b2cbd2"
theme[cpu_mid]="#84d2e6"
theme[cpu_end]="#ffb4ab"

# Mem/Disk free meter
theme[free_start]="#b2cbd2"
theme[free_mid]=""
theme[free_end]="#334a51"

# Mem/Disk cached meter
theme[cached_start]="#bec4eb"
theme[cached_mid]=""
theme[cached_end]="#3e4565"

# Mem/Disk available meter
theme[available_start]="#84d2e6"
theme[available_mid]=""
theme[available_end]="#004e5c"

# Mem/Disk used meter
theme[used_start]="#ffb4ab"
theme[used_mid]=""
theme[used_end]="#93000a"

# Download graph colors
theme[download_start]="#b2cbd2"
theme[download_mid]="#84d2e6"
theme[download_end]="#bec4eb"

# Upload graph colors
theme[upload_start]="#b2cbd2"
theme[upload_mid]="#84d2e6"
theme[upload_end]="#bec4eb"
