background {
    path = /home/z4na14/Documentos/dotfiles/wallpapers/bg5.jpg
    blur_passes = 1
    contrast = 1
    brightness = 0.9
    vibrancy = 1
    vibrancy_darkness = 0.0
}

# GENERAL
general {
    no_fade_in = false
    no_fade_out = false
    grace = 0
    disable_loading_bar = false
}

input-field {
    size = 300, 50
    outline_thickness = 3
    dots_size = 0.33
    dots_spacing = 0.15
    dots_center = true
    dots_rounding = -1
    outer_color = rgba(158, 202, 252, 1)
    inner_color = rgba(16, 20, 24, 1)
    font_color = rgba(224, 226, 232, 1)
    fade_on_empty = true
    fade_timeout = 2000
    placeholder_text = <i><span foreground="#e0e2e8"> Enter Password...</span></i>
    hide_input = false
    rounding = -1
    check_color = rgba(158, 202, 252, 1)
    fail_color = rgba(255, 0, 0, 1)
    fail_transition = 300
    capslock_color = rgba(0, 29, 53, 1)
    numlock_color = rgba(0, 29, 53, 1)
    bothlock_color = rgba(0, 29, 53, 1)
    invert_numlock = false
    swap_font_color = rgba(0, 29, 53, 1)
    position = 0, 100
    halign = center
    valign = bottom
}

# time (hour)
label {
    monitor =
    text = cmd[update:1000] echo "$(date +'%I')"
    color = rgba(158, 202, 252, 1)
    font_size = 200
    font_family = Montserrat Italic Bold
    position = -50, 200
    halign = center
    valign = center
    shadow_passes = 5
    shadow_size = 10
}

# time (minute)
label {
    monitor =
    text = cmd[update:1000] echo "$(date +'%M')"
    color = rgba(158, 202, 252, 1)
    font_size = 200
    font_family = Montserrat Italic Bold
    position = 50, -10
    halign = center
    valign = center
    shadow_passes = 5
    shadow_size = 10
}

# date
label {
    monitor =
    text = cmd[update:1000] echo "$(date +'%d %B, %Y')"
    color = rgba(224, 226, 232, 1)
    font_size = 25
    font_family = Pacifico Regular
    position = 0, -150
    halign = center
    valign = center
    shadow_passes = 5
    shadow_size = 10
}
