# --- Main Colors ---
background            #101418
foreground            #e0e2e8
cursor                #e0e2e8
cursor_text_color     #101418

selection_background  #394857
selection_foreground  #d4e4f6

url_color             #d2bfe7

# --- ANSI Colors ---
color0                #101418
color1                #ffb4ab
color2                #d2bfe7
color3                #b8c8da
color4                #99ccfa
color5                #d2bfe7
color6                #b8c8da
color7                #e0e2e8

color8                #42474e
color9                #93000a
color10               #4f4061
color11               #394857
color12               #094a72
color13               #394857
color14               #4f4061
color15               #c2c7ce

# --- Starship Prompt Bubbles ---
color255              #094a72
color254              #99ccfa
color253              #394857
color252              #b8c8da
color251              #4f4061
color250              #d2bfe7
color249              #93000a
color248              #ffb4ab

color232              #cde5ff
color233              #003352
color234              #d4e4f6
color235              #233240
color236              #eddcff
color237              #382a4a
color238              #ffdad6
color239              #690005
color240              #cde5ff

# Matched with unthemed light/dark
color243              #99ccfa
color244              #ffb4ab
color245              #42474e

# --- UI Elements ---
active_tab_foreground   #003352
active_tab_background   #99ccfa
inactive_tab_foreground #cde5ff
inactive_tab_background #094a72

active_border_color     #99ccfa
inactive_border_color   #8c9198

# --- Marks ---
mark1_foreground        #001d32
mark1_background        #cde5ff
mark2_foreground        #0d1d2a
mark2_background        #d4e4f6
mark3_foreground        #221533
mark3_background        #eddcff
