# --- Main Colors ---
background            #0f1416
foreground            #dee3e5
cursor                #dee3e5
cursor_text_color     #0f1416

selection_background  #334a51
selection_foreground  #cee7ee

url_color             #bec4eb

# --- ANSI Colors ---
color0                #0f1416
color1                #ffb4ab
color2                #bec4eb
color3                #b2cbd2
color4                #84d2e6
color5                #bec4eb
color6                #b2cbd2
color7                #dee3e5

color8                #3f484b
color9                #93000a
color10               #3e4565
color11               #334a51
color12               #004e5c
color13               #334a51
color14               #3e4565
color15               #bfc8cb

# --- Starship Prompt Bubbles ---
color255              #004e5c
color254              #84d2e6
color253              #334a51
color252              #b2cbd2
color251              #3e4565
color250              #bec4eb
color249              #93000a
color248              #ffb4ab

color232              #abedff
color233              #003640
color234              #cee7ee
color235              #1d343a
color236              #dde1ff
color237              #282f4d
color238              #ffdad6
color239              #690005
color240              #abedff

# Matched with unthemed light/dark
color243              #84d2e6
color244              #ffb4ab
color245              #3f484b

# --- UI Elements ---
active_tab_foreground   #003640
active_tab_background   #84d2e6
inactive_tab_foreground #abedff
inactive_tab_background #004e5c

active_border_color     #84d2e6
inactive_border_color   #899295

# --- Marks ---
mark1_foreground        #001f26
mark1_background        #abedff
mark2_foreground        #061f24
mark2_background        #cee7ee
mark3_foreground        #131a37
mark3_background        #dde1ff
