# --- Main Colors ---
background            #0f1417
foreground            #dfe3e7
cursor                #dfe3e7
cursor_text_color     #0f1417

selection_background  #374955
selection_foreground  #d1e5f4

url_color             #cbc1e9

# --- ANSI Colors ---
color0                #0f1417
color1                #ffb4ab
color2                #cbc1e9
color3                #b6c9d7
color4                #90cef4
color5                #cbc1e9
color6                #b6c9d7
color7                #dfe3e7

color8                #41484d
color9                #93000a
color10               #494263
color11               #374955
color12               #004c6a
color13               #374955
color14               #494263
color15               #c0c7cd

# --- Starship Prompt Bubbles ---
color255              #004c6a
color254              #90cef4
color253              #374955
color252              #b6c9d7
color251              #494263
color250              #cbc1e9
color249              #93000a
color248              #ffb4ab

color232              #c4e7ff
color233              #00344a
color234              #d1e5f4
color235              #20333e
color236              #e7deff
color237              #322c4c
color238              #ffdad6
color239              #690005
color240              #c4e7ff

# Matched with unthemed light/dark
color243              #90cef4
color244              #ffb4ab
color245              #41484d

# --- UI Elements ---
active_tab_foreground   #00344a
active_tab_background   #90cef4
inactive_tab_foreground #c4e7ff
inactive_tab_background #004c6a

active_border_color     #90cef4
inactive_border_color   #8b9297

# --- Marks ---
mark1_foreground        #001e2d
mark1_background        #c4e7ff
mark2_foreground        #0a1e28
mark2_background        #d1e5f4
mark3_foreground        #1d1736
mark3_background        #e7deff
