return {
  "Senal-D-A-Gunaratna/matugen.nvim",

  lazy = false,
  priority = 1000,

  opts = {
    load_theme = true, -- set this to false to stop the theme from loading
    -- Path to the JSON/JSONC file generated by matugen
    palette_path = "~/.config/nvim/colorscheme.json",
  },
}
