# --- Main Colors ---
background            #0f1417
foreground            #dfe3e7
cursor                #dfe3e7
cursor_text_color     #0f1417

selection_background  #354a53
selection_foreground  #d0e6f2

url_color             #c6c2ea

# --- ANSI Colors ---
color0                #0f1417
color1                #ffb4ab
color2                #c6c2ea
color3                #b4cad6
color4                #8bd0ef
color5                #c6c2ea
color6                #b4cad6
color7                #dfe3e7

color8                #40484c
color9                #93000a
color10               #454364
color11               #354a53
color12               #004d64
color13               #354a53
color14               #454364
color15               #c0c8cd

# --- Starship Prompt Bubbles ---
color255              #004d64
color254              #8bd0ef
color253              #354a53
color252              #b4cad6
color251              #454364
color250              #c6c2ea
color249              #93000a
color248              #ffb4ab

color232              #bde9ff
color233              #003546
color234              #d0e6f2
color235              #1f333c
color236              #e3dfff
color237              #2e2d4d
color238              #ffdad6
color239              #690005
color240              #bde9ff

# Matched with unthemed light/dark
color243              #8bd0ef
color244              #ffb4ab
color245              #40484c

# --- UI Elements ---
active_tab_foreground   #003546
active_tab_background   #8bd0ef
inactive_tab_foreground #bde9ff
inactive_tab_background #004d64

active_border_color     #8bd0ef
inactive_border_color   #8a9297

# --- Marks ---
mark1_foreground        #001f2a
mark1_background        #bde9ff
mark2_foreground        #081e27
mark2_background        #d0e6f2
mark3_foreground        #191836
mark3_background        #e3dfff
