# --- Main Colors ---
background            #111318
foreground            #e2e2e9
cursor                #e2e2e9
cursor_text_color     #111318

selection_background  #3e4759
selection_foreground  #dae2f9

url_color             #ddbce0

# --- ANSI Colors ---
color0                #111318
color1                #ffb4ab
color2                #ddbce0
color3                #bec6dc
color4                #aac7ff
color5                #ddbce0
color6                #bec6dc
color7                #e2e2e9

color8                #44474e
color9                #93000a
color10               #573e5c
color11               #3e4759
color12               #284777
color13               #3e4759
color14               #573e5c
color15               #c4c6d0

# --- Starship Prompt Bubbles ---
color255              #284777
color254              #aac7ff
color253              #3e4759
color252              #bec6dc
color251              #573e5c
color250              #ddbce0
color249              #93000a
color248              #ffb4ab

color232              #d7e3ff
color233              #0b305f
color234              #dae2f9
color235              #283141
color236              #fad8fd
color237              #3f2844
color238              #ffdad6
color239              #690005
color240              #d7e3ff

# Matched with unthemed light/dark
color243              #aac7ff
color244              #ffb4ab
color245              #44474e

# --- UI Elements ---
active_tab_foreground   #0b305f
active_tab_background   #aac7ff
inactive_tab_foreground #d7e3ff
inactive_tab_background #284777

active_border_color     #aac7ff
inactive_border_color   #8e9099

# --- Marks ---
mark1_foreground        #001b3e
mark1_background        #d7e3ff
mark2_foreground        #131c2b
mark2_background        #dae2f9
mark3_foreground        #28132e
mark3_background        #fad8fd
