# --- Main Colors ---
background            #121318
foreground            #e3e1e9
cursor                #e3e1e9
cursor_text_color     #121318

selection_background  #434659
selection_foreground  #dfe1f9

url_color             #e5bad8

# --- ANSI Colors ---
color0                #121318
color1                #ffb4ab
color2                #e5bad8
color3                #c3c5dd
color4                #bac3ff
color5                #e5bad8
color6                #c3c5dd
color7                #e3e1e9

color8                #46464f
color9                #93000a
color10               #5d3c55
color11               #434659
color12               #394379
color13               #434659
color14               #5d3c55
color15               #c6c5d0

# --- Starship Prompt Bubbles ---
color255              #394379
color254              #bac3ff
color253              #434659
color252              #c3c5dd
color251              #5d3c55
color250              #e5bad8
color249              #93000a
color248              #ffb4ab

color232              #dee1ff
color233              #222c61
color234              #dfe1f9
color235              #2c2f42
color236              #ffd7f2
color237              #44263e
color238              #ffdad6
color239              #690005
color240              #dee1ff

# Matched with unthemed light/dark
color243              #bac3ff
color244              #ffb4ab
color245              #46464f

# --- UI Elements ---
active_tab_foreground   #222c61
active_tab_background   #bac3ff
inactive_tab_foreground #dee1ff
inactive_tab_background #394379

active_border_color     #bac3ff
inactive_border_color   #90909a

# --- Marks ---
mark1_foreground        #0a164b
mark1_background        #dee1ff
mark2_foreground        #171a2c
mark2_background        #dfe1f9
mark3_foreground        #2d1228
mark3_background        #ffd7f2
