[config]

[config.wallpaper]
set = true
command = "awww img --transition-type center {{ image }}"

[templates.hyprland]
input_path = '~/.config/matugen/templates/hyprland-colors.lua'
output_path = '~/.config/hypr/modules/colors.lua'

[templates.hyprlock]
input_path = '~/.config/matugen/templates/hyprlock-colors.conf'
output_path = '~/.config/hypr/hyprlock.conf'

[templates.waybar]
input_path = '~/.config/matugen/templates/waybar-colors.css'
output_path = '~/.config/waybar/colors.css'
post_hook = 'systemctl --user restart waybar.service'

[templates.firefox]
input_path = '~/.config/matugen/templates/firefox-colors.css'
output_path = '~/Documentos/dotfiles/firefox/chrome-firefox/userChrome.css'

[templates.thunderbird]
input_path = '~/.config/matugen/templates/thunderbird-colors.css'
output_path = '~/Documentos/dotfiles/firefox/chrome-thunderbird/userChrome.css'

[templates.gtk3]
input_path = '~/.config/matugen/templates/gtk-colors.css'
output_path = '~/.config/gtk-3.0/colors.css'
post_hook = 'gsettings set org.gnome.desktop.interface gtk-theme ""; gsettings set org.gnome.desktop.interface gtk-theme adw-gtk3-{{mode}}'

[templates.gtk4]
input_path = '~/.config/matugen/templates/gtk-colors.css'
output_path = '~/.config/gtk-4.0/colors.css'
post_hook = '~/.config/matugen/gtk-themes-reload.sh'

[templates.qt5ct]
input_path = '~/.config/matugen/templates/qtct-colors.css'
output_path = '~/.config/qt5ct/colors/matugen.conf'

[templates.qt6ct]
input_path = '~/.config/matugen/templates/qtct-colors.css'
output_path = '~/.config/qt6ct/colors/matugen.conf'

[templates.kitty]
input_path = '~/.config/matugen/templates/kitty-colors.css'
output_path = '~/.config/kitty/themes/Matugen.conf'
post_hook = "kitty +kitten themes --reload-in=all Matugen"

[templates.zed]
input_path = '~/.config/matugen/templates/zed-colors.json'
output_path = '~/.config/zed/themes/matugen.json'

[templates.fuzzel]
input_path = '~/.config/matugen/templates/fuzzel-colors.ini'
output_path = '~/.config/fuzzel/colors.ini'

[templates.mako]
input_path = '~/.config/matugen/templates/mako-colors'
output_path = '~/.config/mako/mako-colors'
post_hook = 'makoctl reload'

[templates.vesktop]
input_path = '~/.config/matugen/templates/discord-colors.css'
output_path = '~/.config/vesktop/themes/midnight-discord.css'

[templates.obsidian]
input_path = '~/.config/matugen/templates/obsidian-colors.css'
output_path = '~/Documentos/personal-vlt/.obsidian/snippets/matugen.css'

[templates.zathura]
input_path = '~/.config/matugen/templates/zathura-colors'
output_path = '~/.config/zathura/zathurarc'

[templates.btop]
input_path = '~/.config/matugen/templates/btop-colors.theme'
output_path = '~/.config/btop/themes/matugen.theme'
post_hook = 'pkill -USR2 btop || true'

[templates.obs]
input_path = '~/.config/matugen/templates/obs-colors.obt'
output_path = '~/.config/obs-studio/themes/matugen.obt'

[templates.millennium]
input_path = '~/.config/matugen/templates/steam-colors.css'
output_path = '~/.steam/steam/millennium/themes/Material-Theme/css/main/colors/matugen.css'

